import { projects } from './data/projects.js';
import './styles.css';

const arrow = '<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h12M10 4l6 6-6 6"/></svg>';
const moon = '<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M16.7 12.1A7.5 7.5 0 0 1 7.9 3.3a7.6 7.6 0 1 0 8.8 8.8Z"/></svg>';
const sun = '<svg viewBox="0 0 20 20" aria-hidden="true"><circle cx="10" cy="10" r="3.5"/><path d="M10 1.5v2M10 16.5v2M1.5 10h2m13 0h2M4 4l1.4 1.4m9.2 9.2L16 16M16 4l-1.4 1.4M5.4 14.6 4 16"/></svg>';
const projectCards = projects.map((project, index) =>
  '<article class="project-card"><div class="project-card__top"><span class="project-index">0' +
  (index + 1) + '</span><span class="status-pill"><span></span>' + project.status +
  '</span></div><p class="eyebrow">' + project.category + '</p><h3>' + project.name +
  '</h3><p class="project-card__description">' + project.description +
  '</p><ul class="tag-list" aria-label="Technologies and focus areas">' +
  project.stack.map((item) => '<li>' + item + '</li>').join('') +
  '</ul><a class="text-link" href="#contact">Discuss a similar idea ' + arrow + '</a></article>'
).join('');

const page = [
'<header class="site-header"><div class="container header-inner"><a class="brand" href="#top" aria-label="Coderaft Labs home"><span class="brand-mark" aria-hidden="true">C</span><span class="brand-name">coderaft<span>labs</span></span></a><nav class="primary-nav" id="primary-nav" aria-label="Main navigation"><a href="#work">Work</a><a href="#capabilities">Capabilities</a><a href="#about">About</a><a href="#contact">Contact</a></nav><div class="header-actions"><button class="theme-toggle" type="button" aria-label="Switch to dark theme">' + moon + '</button><a class="button button--small button--dark header-cta" href="#contact">Let’s talk ' + arrow + '</a><button class="menu-toggle" type="button" aria-controls="primary-nav" aria-expanded="false" aria-label="Open navigation"><span></span><span></span></button></div></div></header>',
'<main id="main"><section class="hero section" id="top"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow hero-kicker"><span class="status-dot"></span> Independent engineering practice</p><h1>Software that makes<br><span>work move forward.</span></h1><p class="hero-intro">Coderaft Labs builds dependable software, practical AI applications, and automation for real-world work.</p><div class="hero-actions"><a class="button button--accent" href="#work">Explore the work ' + arrow + '</a><a class="text-link" href="#about">A little about the practice ' + arrow + '</a></div><div class="hero-proof"><span class="proof-line"></span><p>Enterprise engineering experience.<br>A practical approach to what comes next.</p></div></div>',
'<div class="hero-art"><div class="art-label"><span>01 / SYSTEMS</span><span>DESIGN · BUILD · IMPROVE</span></div><svg class="systems-map" viewBox="0 0 540 460" role="img" aria-labelledby="map-title map-desc"><title id="map-title">Connected systems, designed with care</title><desc id="map-desc">A central application connected to data, people, tools, and outcomes.</desc><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="currentColor" opacity=".2"/></pattern></defs><rect width="540" height="460" fill="url(#grid)"/><circle cx="270" cy="230" r="152" class="map-orbit"/><circle cx="270" cy="230" r="105" class="map-orbit map-orbit--inner"/><path d="M270 125V68M165 230H93M375 230h71M270 335v57M196 156l-42-42M344 156l42-42M195 304l-42 42M345 304l42 42" class="map-line"/><rect x="206" y="166" width="128" height="128" rx="24" class="map-core"/><path d="M246 204h48M246 222h48M246 240h34M246 258h42" class="map-core-line"/><rect x="237" y="35" width="66" height="52" rx="12" class="map-node"/><rect x="44" y="204" width="82" height="52" rx="12" class="map-node"/><rect x="414" y="204" width="82" height="52" rx="12" class="map-node"/><rect x="237" y="374" width="66" height="52" rx="12" class="map-node"/><circle cx="145" cy="104" r="12" class="map-accent-node"/><circle cx="395" cy="104" r="12" class="map-accent-node"/><circle cx="145" cy="356" r="12" class="map-accent-node"/><circle cx="395" cy="356" r="12" class="map-accent-node"/><text x="270" y="65" class="map-text" text-anchor="middle">DATA</text><text x="85" y="234" class="map-text" text-anchor="middle">PEOPLE</text><text x="455" y="234" class="map-text" text-anchor="middle">TOOLS</text><text x="270" y="404" class="map-text" text-anchor="middle">IMPACT</text></svg><div class="art-caption"><span>Thoughtful by design</span><span>DESIGN · ENGINEERING</span></div></div></div><div class="hero-bottom container"><span>SOFTWARE</span><span>AI APPLICATIONS</span><span>AUTOMATION</span><span class="scroll-note">SCROLL TO EXPLORE <span>↓</span></span></div></section>',
'<section class="build-section section" id="what-i-build"><div class="container"><div class="section-heading section-heading--split"><div><p class="eyebrow">01 / What I build</p><h2>Useful systems, built<br>for the way work happens.</h2></div><p class="section-aside">From a clear first release to the engineering behind systems that need to keep working.</p></div><div class="build-grid"><article class="build-card"><span class="build-number">01</span><h3>Software products</h3><p>Web applications, APIs, and internal tools shaped around a real user need.</p><span class="build-arrow">' + arrow + '</span></article><article class="build-card"><span class="build-number">02</span><h3>AI applications</h3><p>RAG, document workflows, and assistants designed with useful outputs and clear boundaries.</p><span class="build-arrow">' + arrow + '</span></article><article class="build-card"><span class="build-number">03</span><h3>Automation</h3><p>Practical integrations that reduce repetitive work and connect the tools a team already uses.</p><span class="build-arrow">' + arrow + '</span></article><article class="build-card"><span class="build-number">04</span><h3>Engineering improvement</h3><p>Architecture, performance, and delivery improvements for existing software.</p><span class="build-arrow">' + arrow + '</span></article></div></div></section>',
'<section class="work-section section" id="work"><div class="container"><div class="section-heading section-heading--split"><div><p class="eyebrow">02 / Selected work</p><h2>Building in public,<br>one useful tool at a time.</h2></div><p class="section-aside">These are planned showcase builds. Each card will become a case study when there is working software and evidence to share.</p></div><div class="project-grid">' + projectCards + '</div><p class="work-footnote"><span class="status-dot"></span> Planned work is labeled clearly. No demos or outcomes are implied before they exist.</p></div></section>',
'<section class="case-section section" id="case-studies"><div class="container case-layout"><div class="case-intro"><p class="eyebrow">03 / Case studies</p><h2>Show the decisions<br>behind the result.</h2></div><div class="case-content"><p class="case-lead">A finished project should explain more than what it does. It should make the problem, trade-offs, and engineering choices easy to understand.</p><div class="case-steps"><div><span>01</span><p><strong>The problem</strong><br>Who needed what, and why existing ways fell short.</p></div><div><span>02</span><p><strong>The approach</strong><br>Architecture, technology choices, and important trade-offs.</p></div><div><span>03</span><p><strong>The evidence</strong><br>A working demo, source code, screenshots, and known limitations.</p></div></div><p class="case-note">Case studies will be published as projects are completed. The first showcase builds are currently planned.</p></div></div></section>',
'<section class="capabilities-section section" id="capabilities"><div class="container"><div class="section-heading"><p class="eyebrow">04 / Technical capabilities</p><h2>Grounded in engineering.<br>Curious about what’s next.</h2></div><div class="capability-list"><div class="capability-row"><h3>Languages</h3><p>Java · C# / .NET · Python · JavaScript</p></div><div class="capability-row"><h3>Application engineering</h3><p>APIs · distributed systems · microservices · event-driven systems</p></div><div class="capability-row"><h3>AI and data</h3><p>FastAPI · retrieval augmented generation · MCP · agentic workflows · evaluation</p></div><div class="capability-row"><h3>Delivery and quality</h3><p>Architecture · performance · testing · observability · automation</p></div></div><p class="capability-note">Tools and methods are chosen to fit the problem. This is a working overview, not a claim of equal depth in every area.</p></div></section>',
'<section class="experience-section section" id="experience"><div class="container experience-grid"><div><p class="eyebrow">05 / Background</p><h2>Experience with systems<br>that matter.</h2></div><div class="experience-copy"><p>My engineering experience includes enterprise software at Morgan Stanley and Publicis Sapient, with work across financial technology, distributed systems, APIs, and user-facing applications.</p><p>Today, I’m applying that engineering foundation to practical AI applications and automation—building carefully, learning in the open, and sharing the work as it becomes real.</p><div class="company-list" aria-label="Professional experience"><span>Morgan Stanley</span><span>Publicis Sapient</span></div></div></div></section>',
'<section class="about-section section" id="about"><div class="container about-grid"><p class="eyebrow">06 / About</p><div><h2>Good software starts<br>with listening.</h2><p>I’m a software engineer who enjoys turning ambiguous problems into dependable tools. I bring a hands-on approach, clear communication, and respect for the details that make software useful after launch.</p><p>Coderaft Labs brings together years of engineering experience and a growing body of work in AI and automation.</p></div><div class="about-signature"><span class="signature-mark">C<span>.</span></span><span>CODERAFT LABS<br>SOFTWARE · AI · AUTOMATION</span></div></div></section>',
'<section class="contact-section section" id="contact"><div class="container contact-panel"><div><p class="eyebrow">07 / Work with me</p><h2>Have a useful problem<br>to work through?</h2><p>Tell me what you’re trying to improve. We can figure out whether software, AI, or automation is the right fit.</p></div><div class="contact-actions"><a class="button button--light" href="mailto:tilak.techmail@gmail.com">Start a conversation <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h12M10 4l6 6-6 6"/></svg></a><a href="https://www.linkedin.com/in/tilak-2b9a3651/" target="_blank" rel="noreferrer">Connect on LinkedIn</a><span>Focused software and automation projects</span></div><span class="contact-watermark" aria-hidden="true">C</span></div></section></main>',
'<footer class="site-footer"><div class="container footer-inner"><a class="brand" href="#top"><span class="brand-mark" aria-hidden="true">C</span><span class="brand-name">coderaft<span>labs</span></span></a><p>Useful systems. Thoughtful engineering.</p><span>© <span id="year"></span> Coderaft Labs</span></div></footer>'
].join('');
document.querySelector('#app').innerHTML = page;

const root = document.documentElement;
const themeButton = document.querySelector('.theme-toggle');
const preferredTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
function setTheme(value) {
  root.dataset.theme = value;
  themeButton.setAttribute('aria-label', 'Switch to ' + (value === 'dark' ? 'light' : 'dark') + ' theme');
  themeButton.innerHTML = value === 'dark' ? sun : moon;
  document.querySelector('meta[name="theme-color"]').content = value === 'dark' ? '#171b1a' : '#f4f3ee';
}
setTheme(localStorage.getItem('coderaft-theme') || preferredTheme);
themeButton.addEventListener('click', () => {
  const next = root.dataset.theme === 'dark' ? 'light' : 'dark';
  localStorage.setItem('coderaft-theme', next);
  setTheme(next);
});
const menuButton = document.querySelector('.menu-toggle');
const navigation = document.querySelector('#primary-nav');
menuButton.addEventListener('click', () => {
  const open = menuButton.getAttribute('aria-expanded') === 'true';
  menuButton.setAttribute('aria-expanded', String(!open));
  menuButton.setAttribute('aria-label', open ? 'Open navigation' : 'Close navigation');
  navigation.classList.toggle('is-open', !open);
});
navigation.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => {
  menuButton.setAttribute('aria-expanded', 'false');
  menuButton.setAttribute('aria-label', 'Open navigation');
  navigation.classList.remove('is-open');
}));
document.querySelector('#year').textContent = String(new Date().getFullYear());
